# Generated by Django 3.1.2 on 2021-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=70)),
                ('surname', models.CharField(default=None, max_length=64)),
                ('address', models.CharField(default=None, max_length=64)),
                ('phone_number', models.IntegerField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(blank=True, default=None, max_length=64)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
