# Generated by Django 3.1.2 on 2021-11-02 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Contact name')),
                ('surname', models.CharField(default=None, max_length=64)),
                ('address', models.CharField(default=None, max_length=64)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=64)),
                ('url', models.URLField(blank=True, default=None)),
                ('image', models.ImageField(blank=True, default=None, max_length=64, upload_to='')),
            ],
        ),

    ]
